### ISSUE TITLE
Wrong Desc at C3:Logic

### ISSUE THREAD

**Issue by WilliamQiufeng** [tanpero/JavaScript-Art-Tour#2]
At This part, it is told that ***constant*** `undefined` is *changeable*.  
However, After Trying *This example*, I've found out that it was wrong.  
```javascript
undefined=1;//doesn't change because it is a constant
console.log(undefined);//undefined
```

**Comment by tanpero** [comment]
It had Fixed.

**Comment by tanpero** [comment]
>

**Comment by tanpero** [comment]
![image](https://user-images.githubusercontent.com/46063801/54875464-d0395a00-4e3a-11e9-9654-8719b3459060.png)
